config/routes.rb
Railbook::Application.routes.draw do
  resources :reviews

  root :to => 'books#index'
  
  devise_for :users
  get 'books', :to => 'books#index', :as => :user_root

  resources :books do
    put :finish, :on => :member
    put :unfinish, :on => :member
    get :done, :on => :collection
  end

  match 'books/:id/:book_id/:file' => 'books#image',:constraints => { :file => /.*/ }, :as => :book_image

  match ':controller(/:action(/:id(.:format)))'
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews
  has_many :book_images
end

app/controllers/books_controller.rb
#coding: utf-8

require 'kconv'

class BooksController < ApplicationController
  before_filter :authenticate_user!, :only => ['new','edit','destroy']

  # GET /books
  # GET /books.json
  def index
    #@books = Book.all
    @books = Book.find(:all, :order => "isbn")
    @book_images = BookImage.find(:all, :include => :book)
    #@book_images = []

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @review = Review.find_all_by_book_id(@book.id)
    @book_image = BookImage.find_all_by_book_id(@book.id)

    #レビュー投稿用にセッションにbook_idを保持
    session[:book_id] = @book.id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    #@book_image = BookImage.find_all_by_book_id(@book.id)
    @book_image = @book.book_images
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
    @book_image = @book.book_images.build()

    #アップロード処理
    self.upload_pics

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])
    @book_image = BookImage.new(params[:book_image])

    #アップロード処理
    ret = self.upload_pics

    ActiveRecord::Base.transaction do
      @book.update_attributes(params[:book])
      if ret == 1
        @book.book_images << @book_image
      end
      flash[:notice] = '変更を保存しました。'
      redirect_to :action => 'show', :id => @book
    end

#    respond_to do |format|
#      if @book.update_attributes(params[:book])
#        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
#        format.json { head :ok }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @book.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
    end 
  end

  def list
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  def upload_pics

    #アップロード処理
    if params[:book_image].blank?
      return 0
    else
      file = params[:book_image][:image_name]
      name = file.original_filename
      #新規登録用
      @book_image.image_name = "#{name}"
      #更新用
      params[:book_image][:image_name] = "#{name}"

      perms = ['.jpg','.jpeg','.gif','.png','.bmp']

      if !perms.include?(File.extname(name).downcase)
        result = 'アップロードできるのは画像ファイルのみです。'

      elsif file.size > 1.megabyte
        result = 'ファイルサイズは1MBまでです。'
      else
        name = name.kconv(Kconv::SJIS, Kconv::UTF8)
        File.open("/home/nagatsuka/railbook_contents/#{name}", 'wb'){|f| f.write(file.read)}
        #result = "#{name.toutf8}をアップロードしました。"
      end
      return 1
    end
      
  end

  def image
    if params[:file].blank?
      render :nothing => true, :status => 404
      return
    end

    path = File.join(SYSTEM_CONFIG[:image_dir],
      params[:id],
      params[:book_id],
      params[:file])
    send_file path,:type => 'image/jpeg', :disposition => 'inline'
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html (コピー).erb
<%= form_for(@book, :multipart => true) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :publish %><br />
    <%= f.text_field :publish %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.date_select :publisher %>
  </div>
  <div class="field">
    <%= f.label :cd %><br />
    <%= f.check_box :cd %>
  </div>
  <div class="field">
    <%= file_field 'upfile', {:size => 50} %> 
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_for(@book, :html => {:multipart => true}) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @book_image %>
    <table>
      <tr>
        <%= render @book_image %>
      </tr>
    </table>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :publish %><br />
    <%= f.text_field :publish %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.date_select :publisher %>
  </div>
  <div class="field">
    <%= f.label :cd %><br />
    <%= f.check_box :cd %>
  </div>

  <%= fields_for :book_image do |bi| %>
    <div class="field">
      <%= bi.label :image %><br />
      <%= bi.file_field :image_name %>
    </div>
  <% end %>

  <%#*<div class="field">%>
    <%# if @book.img_url != nil%>
      <%#= image_tag (@book.img_url)%>
    <%# end %>

    <%#= f.label :image %><br />
    <%#= f.file_field :img_url %>
  <%#*</div>%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<%#*<h1>Listing books</h1>%>
<%= image_tag "title_image.JPG" %>
<hr/>

<div class="main">
  <table border="0">
    <% @books.each do |book| %>
      <tr style="background-color:<%= cycle('#FFffFF','#FFff99') %> ">
        <td>
          <% if book.book_images[0] %>
            <%if book.book_images[0].image_name != nil%>
              <%#= image_tag book.book_images[0].image_name, :width => "120" %>
          <%= book_image_tag(book.id,book.book_images[0].id,book.book_images[0].image_name,120) %>
            <% elsif %>
              <%= image_tag "no-image.jpg", :width => "120"%>
            <% end  %>
          <% elsif %>
            <%= image_tag "no-image.jpg", :width => "120"%>
          <% end %>
        </td>

        <td>
          <h2><%= book.title %></h2>
          <%= book.publish %><br/>
          <%= number_to_currency(book.price, :unit => '￥', :precision => 0) %>&nbsp;&nbsp;
          発行：<%= book.publisher %>&nbsp;&nbsp;
          ISBN :<%= book.isbn %><br/>
          CD：<%= book.cd %>
        </td>

        <td><%= link_to 'Show', book %><br/>
          <%= link_to 'Edit', edit_book_path(book) %><br/>
          <%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>
<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/list.html.erb
<table border="1">
  <tr>
    <th>ISBNコード</th><th>書名</th><th>価格</th>
    <th>出版社</th><th>刊行日</th><th>CD-ROM</th>
  </tr>

  <% @books.each do |book|%>
    <tr>
      <td><%= book.isbn %></td>
      <td><%= book.title %></td>
      <td><%= book.price %></td>
      <td><%= book.publish %></td>
      <td><%= book.published %></td>
      <td><%= book.cd %></td>
      <% if book_images.image_name == nil%>
        <td><%= image_tag (book_images.image_name)%> </td>
      <% else %>
        <td><%= image_tag ("no-image.jpg")%></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<h1>New book</h1>

  <%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <%= render @book_image %>
</p>
<p>
  <b>Isbn:</b>
  <%= @book.isbn %>
</p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Price:</b>
  <%= @book.price %>
</p>

<p>
  <b>Publish:</b>
  <%= @book.publish %>
</p>

<p>
  <b>Publisher:</b>
  <%= @book.publisher %>
</p>

<p>
  <b>Cd:</b>
  <%= @book.cd %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %> |
<%= link_to 'post your review', new_review_path %>

<br/>
<br/>
<hr/>
<div>この本のレビュー一覧</div>

<div>
  <% if @review.empty? %>
    <div> まだレビューはありません。</div>
  <% else %>
    <table border="1">
      <tr>
        <td>投稿者</td>
        <td>タイトル</td>
        <td>本文</td>
      </tr>
      <%= render @review %>
    </table>

  <% end %>
</div>